defaults:
  - data: cfg/libero_all/img
  - model: stable_vae_model
  - _self_

# experiment
experiment_folder: libero_vae
experiment_name: vae_all64

# train params
batch_size: 256
n_workers: 16
device_prefetch_size: 4
n_grad_steps: 300000
log_every_step: 50
dump_every_step: 200
warmup_steps: 1000
lr: 1e-4
end_lr: 1e-6

# eval params
eval_every_step: 25000
eval_traj_frames: 32
n_eval_episodes: 4
n_eval_processes: 4
render_video: true
n_videos: 5
save_verbose: true

# data params (single-frame VAE training)
horizon: 1
obs_horizon: 1
action_horizon: 1

# snapshot
snapshot_dir: ./checkpoints
save_every_step: 25000
restore_snapshot_path: null

# misc
seed: 1
save_video: false
use_tb: true
use_wandb: false
name: train_vae_libero

hydra:
  run:
    dir: ./experiments/${experiment_folder}/${experiment_name}
